# Serializer
services:
    App\Domain\Models\Normalizer\CompanyNormalizer:
        class: App\Domain\Models\Normalizer\CompanyNormalizer
        tags:
            - { name: serializer.normalizer, priority: 128 }
